// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DineGO_Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250324093413_InitalDB_V1.02")]
    partial class InitalDB_V102
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DineGO_Api.Model.Admin", b =>
                {
                    b.Property<int>("ad_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ad_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ad_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ad_password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ad_username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ad_id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("DineGO_Api.Model.Blog", b =>
                {
                    b.Property<int>("blog_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("blog_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("blog_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog_information")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("blog_title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("resOwner_id")
                        .HasColumnType("int");

                    b.HasKey("blog_id");

                    b.HasIndex("resOwner_id");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("DineGO_Api.Model.Category", b =>
                {
                    b.Property<int>("cate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cate_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cate_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("cate_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("DineGO_Api.Model.Customer", b =>
                {
                    b.Property<int>("cus_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cus_address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("cus_birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("cus_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cus_gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cus_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cus_isKYI")
                        .HasColumnType("bit");

                    b.Property<string>("cus_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cus_password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cus_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cus_username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("cus_id");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("DineGO_Api.Model.Notification", b =>
                {
                    b.Property<int>("noti_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cus_id")
                        .HasColumnType("int");

                    b.Property<string>("noti_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("noti_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("noti_title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("noti_type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("noti_id");

                    b.HasIndex("cus_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("DineGO_Api.Model.Payment", b =>
                {
                    b.Property<int>("pay_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cus_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("pay_createdDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("pay_price")
                        .HasColumnType("float");

                    b.Property<string>("pay_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reser_id")
                        .HasColumnType("int");

                    b.HasKey("pay_id");

                    b.HasIndex("cus_id");

                    b.HasIndex("reser_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("DineGO_Api.Model.Reservation", b =>
                {
                    b.Property<int>("reser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cus_id")
                        .HasColumnType("int");

                    b.Property<int>("res_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("reser_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("reser_note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reser_quantity")
                        .HasColumnType("int");

                    b.Property<string>("reser_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("reser_id");

                    b.HasIndex("cus_id");

                    b.HasIndex("res_id");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("DineGO_Api.Model.Restaurant", b =>
                {
                    b.Property<int>("res_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cate_id")
                        .HasColumnType("int");

                    b.Property<int>("resOwner_id")
                        .HasColumnType("int");

                    b.Property<string>("res_address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("res_discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("res_images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("res_information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("res_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("res_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("res_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("res_rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("res_id");

                    b.HasIndex("cate_id");

                    b.HasIndex("resOwner_id");

                    b.ToTable("restaurants");
                });

            modelBuilder.Entity("DineGO_Api.Model.RestaurantOwner", b =>
                {
                    b.Property<int>("resOwner_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cus_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("resOwner_createdDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("resOwner_isAuthorize")
                        .HasColumnType("bit");

                    b.Property<string>("resOwner_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("resOwner_id");

                    b.HasIndex("cus_id");

                    b.ToTable("restaurantOwners");
                });

            modelBuilder.Entity("DineGO_Api.Model.Blog", b =>
                {
                    b.HasOne("DineGO_Api.Model.RestaurantOwner", "restaurantOwner")
                        .WithMany("blogs")
                        .HasForeignKey("resOwner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("restaurantOwner");
                });

            modelBuilder.Entity("DineGO_Api.Model.Notification", b =>
                {
                    b.HasOne("DineGO_Api.Model.Customer", "customer")
                        .WithMany("notifications")
                        .HasForeignKey("cus_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("DineGO_Api.Model.Payment", b =>
                {
                    b.HasOne("DineGO_Api.Model.Customer", "customer")
                        .WithMany("payments")
                        .HasForeignKey("cus_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineGO_Api.Model.Reservation", "reservation")
                        .WithMany("payments")
                        .HasForeignKey("reser_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("reservation");
                });

            modelBuilder.Entity("DineGO_Api.Model.Reservation", b =>
                {
                    b.HasOne("DineGO_Api.Model.Customer", "customer")
                        .WithMany("reservations")
                        .HasForeignKey("cus_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineGO_Api.Model.Restaurant", "restaurant")
                        .WithMany("reservations")
                        .HasForeignKey("res_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("restaurant");
                });

            modelBuilder.Entity("DineGO_Api.Model.Restaurant", b =>
                {
                    b.HasOne("DineGO_Api.Model.Category", "category")
                        .WithMany("restaurants")
                        .HasForeignKey("cate_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineGO_Api.Model.RestaurantOwner", "restaurantOwner")
                        .WithMany("restaurants")
                        .HasForeignKey("resOwner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("restaurantOwner");
                });

            modelBuilder.Entity("DineGO_Api.Model.RestaurantOwner", b =>
                {
                    b.HasOne("DineGO_Api.Model.Customer", "customer")
                        .WithMany("restaurantOwners")
                        .HasForeignKey("cus_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("DineGO_Api.Model.Category", b =>
                {
                    b.Navigation("restaurants");
                });

            modelBuilder.Entity("DineGO_Api.Model.Customer", b =>
                {
                    b.Navigation("notifications");

                    b.Navigation("payments");

                    b.Navigation("reservations");

                    b.Navigation("restaurantOwners");
                });

            modelBuilder.Entity("DineGO_Api.Model.Reservation", b =>
                {
                    b.Navigation("payments");
                });

            modelBuilder.Entity("DineGO_Api.Model.Restaurant", b =>
                {
                    b.Navigation("reservations");
                });

            modelBuilder.Entity("DineGO_Api.Model.RestaurantOwner", b =>
                {
                    b.Navigation("blogs");

                    b.Navigation("restaurants");
                });
#pragma warning restore 612, 618
        }
    }
}
